export const tasksTypes = {
    ADD_TASK_START: 'ADD_TASK_START',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',

    CHANGE_TASKS_ORDER: 'CHANGE_TASKS_ORDER',
    DELETE_TASK: 'DELETE_TASK',
    START_TASK_TIMER: 'START_TASK_TIMER'
};
