export const projectTypes = {
    ADD_PROJECT_START: 'ADD_PROJECT_START',
    ADD_PROJECT_SUCCESS: 'ADD_PROJECT_SUCCESS',
    ADD_PROJECT_FAILURE: 'ADD_PROJECT_FAILURE',

    DELETE_PROJECT_START: 'DELETE_PROJECT_START',
    DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',
    DELETE_PROJECT_FAILURE: 'DELETE_PROJECT_FAILURE'
}
